include $(GOROOT)/src/Make.$(GOARCH)

TARG = socketio
GOFILES = \
	util.go \
	broadcaster.go \
	socketio.go \
	connection.go \
	formatter.go \
	transport.go \
	transport_xhrpolling.go \
	transport_xhrmultipart.go \
	transport_websocket.go
	

include $(GOROOT)/src/Make.pkg
