include $(GOROOT)/src/Make.inc

TARG = socketio
GOFILES = \
	util.go \
	message.go \
	config.go \
	session.go \
	socketio.go \
	connection.go \
	codec.go \
	siocodec.go \
	transport.go \
	transport_xhrpolling.go \
	transport_xhrmultipart.go \
	transport_htmlfile.go \
	transport_websocket.go \
	transport_flashsocket.go \
	transport_jsonppolling.go \
	client.go \
	

include $(GOROOT)/src/Make.pkg
